# Generated by Django 5.2 on 2025-04-24 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_name', models.CharField(max_length=64, unique=True, verbose_name='Название подразделения')),
                ('base_addres', models.CharField(max_length=255, verbose_name='Адрес подразделения')),
            ],
            options={
                'verbose_name': 'Подразделение',
                'verbose_name_plural': 'Подразделения',
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('Y', 'Введено в эксплуатацию'), ('N', 'Снято с учёта')], default='Y', max_length=2, verbose_name='Состояние учёта')),
                ('objects_name', models.CharField(max_length=128, verbose_name='Инвентаризационный объект')),
                ('inventory_number', models.CharField(max_length=50, unique=True, verbose_name='Инвентаризационный номер')),
                ('value', models.CharField(max_length=500, verbose_name='Счёт')),
                ('office', models.CharField(default='0', verbose_name='Кабинет расположения')),
                ('accountable_user', models.CharField(max_length=255, verbose_name='Отвественный за содержание')),
                ('start_data', models.CharField(max_length=64, verbose_name='Дата ввода в эксплуатацию')),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.baseinfo', verbose_name='Подразделение')),
            ],
            options={
                'verbose_name': 'Инвентаризационные данные',
                'verbose_name_plural': 'Инвентаризационные данные',
            },
        ),
        migrations.CreateModel(
            name='QrCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr', models.ImageField(upload_to='qr_codes/', verbose_name='QR-код')),
                ('objects_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='data.inventoryitem', verbose_name='Инвентарный объект')),
            ],
        ),
    ]
