# Generated by Django 5.2 on 2025-04-24 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='state',
            field=models.CharField(choices=[('Y', 'Введено в эксплуатацию'), ('N', 'Снято с учёта')], default='Введено в эксплуатацию', max_length=2, verbose_name='Состояние учёта'),
        ),
    ]
