# Generated by Django 5.2 on 2025-04-20 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='base',
            options={'verbose_name': 'Подразделение', 'verbose_name_plural': 'Подразделения'},
        ),
        migrations.AlterModelOptions(
            name='inventoryitem',
            options={'verbose_name': 'Инвентаризационные данные', 'verbose_name_plural': 'Инвентаризационные данные'},
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='user_name',
            field=models.CharField(default='Неизвестный', max_length=255, verbose_name='Отвественный за содержание'),
        ),
        migrations.AlterField(
            model_name='base',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Адрес подразделения'),
        ),
        migrations.AlterField(
            model_name='base',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Название подразделения'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.base', verbose_name='Подразделение'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='inventory_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='Инвентарный номер'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Наименование оборудования'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='office',
            field=models.SmallIntegerField(verbose_name='Кабинет расположения'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='qr',
            field=models.ImageField(upload_to='qr_codes/', verbose_name='QR-код'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость'),
        ),
    ]
