# Generated by Django 5.2 on 2025-05-02 04:01

import data.validate
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='inventoryitem',
            name='data_invent_invento_999d17_idx',
        ),
        migrations.RemoveIndex(
            model_name='inventoryitem',
            name='data_invent_state_cabb54_idx',
        ),
        migrations.RemoveIndex(
            model_name='inventoryitem',
            name='data_invent_base_id_43f61b_idx',
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='current_duration',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Срок эксплуатации (дни)'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='description',
            field=models.TextField(default='Здесь должно быть описание объекта, позволяющее легко его идентифицировать.\n                    Здесь могут быть его характеристики, цвет, объем, системные данные и т.п.', validators=[data.validate.validate_description_length], verbose_name='Описание'),
        ),
    ]
