# Generated by Django 5.2 on 2025-05-01 16:05

import data.validate
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseinfo',
            name='base_addres',
        ),
        migrations.AddField(
            model_name='baseinfo',
            name='base_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Адрес подразделения'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='current_duration',
            field=models.CharField(blank=True, max_length=5, verbose_name='Срок эксплуатации'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='discription',
            field=models.TextField(default='Здесь должно быть описание объекта, позволяющее лего его идентифицировать\n                                   Здесь могут быть его характеристики, цвет, объем системные данные и т.п.', validators=[data.validate.validate_description_length], verbose_name='Описание'),
        ),
    ]
