# Generated by Django 5.2 on 2025-04-27 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='inventory_number',
            field=models.CharField(help_text='Введите значение до 12 цифр'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='state',
            field=models.CharField(choices=[('Введено в эксплуатацию', 'Введено в эксплуатацию'), ('Снято с учёта', 'Снято с учёта')], default='Введено в эксплуатацию', max_length=40, verbose_name='Состояние учёта'),
        ),
    ]
