# Generated by Django 5.2 on 2025-05-02 09:56

import data.validate
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_remove_inventoryitem_data_invent_invento_999d17_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseinfo',
            name='base_address',
            field=models.CharField(max_length=255, verbose_name='Адрес подразделения'),
        ),
        migrations.AlterField(
            model_name='baseinfo',
            name='base_name',
            field=models.CharField(max_length=64, unique=True, verbose_name='Название подразделения'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='accountable_user',
            field=models.CharField(max_length=255, verbose_name='Ответственный за содержание'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='current_duration',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Срок эксплуатации (дни)'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='inventory_number',
            field=models.CharField(max_length=12, unique=True, validators=[data.validate.validate_number_int], verbose_name='Инвентаризационный номер'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='objects_name',
            field=models.CharField(max_length=128, verbose_name='Инвентаризационный объект'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='office',
            field=models.CharField(default='0', max_length=10, verbose_name='Кабинет расположения'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='start_date',
            field=models.DateField(verbose_name='Дата ввода в эксплуатацию'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='value',
            field=models.CharField(choices=[('Здания и сооружения', [('101.12.00.00', '101.12 - Нежилые помещения (здания и сооружения) - недвижимое имущество'), ('103.11.00.00', '103.11 - Земля (земельные участки) - недвижимое имущество')]), ('Машины и оборудование (особо ценное)', [('101.22.00.00', '101.22 - Нежилые помещения (здания и сооружения) - особо ценное движимое имущество'), ('101.24.00.00', '101.24 - Машины и оборудование - особо ценное движимое имущество')]), ('Машины и оборудование (иное)', [('101.34.00.00', '101.34 - Машины и оборудование - иное движимое имущество'), ('21.34.00.00', '21.34 - Машины и оборудование - иное движимое имущество')]), ('Инвентарь и хозяйственные принадлежности', [('101.36.00.00', '101.36 - Инвентарь производственный и хозяйственный - иное движимое имущество'), ('21.36.00.00', '21.36 - Инвентарь производственный и хозяйственный - иное движимое имущество')]), ('Прочие основные средства', [('101.38.00.00', '101.38 - Прочие основные средства - иное движимое имущество')]), ('Биологические ресурсы', [('101.27.00.00', '101.27 - Биологические ресурсы - особо ценное движимое имущество')])], max_length=20, verbose_name='Счёт актива'),
        ),
    ]
