# Generated by Django 5.2 on 2025-04-20 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_alter_base_options_alter_inventoryitem_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='qr',
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='user_name',
            field=models.CharField(default='Ответсвенный за содержание', max_length=255, verbose_name='Отвественный за содержание'),
        ),
        migrations.CreateModel(
            name='QrCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr', models.ImageField(upload_to='qr_codes/', verbose_name='QR-код')),
                ('objects_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='data.inventoryitem', verbose_name='Инвентаризационные данные')),
            ],
        ),
    ]
