# Generated by Django 5.2 on 2025-04-24 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_alter_inventoryitem_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='inventory_number',
            field=models.CharField(max_length=50, verbose_name='Инвентаризационный номер'),
        ),
    ]
