# Generated by Django 5.2 on 2025-04-20 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_remove_inventoryitem_qr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='objects_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='data.inventoryitem', verbose_name='Инвентарный объект'),
        ),
    ]
