# Generated by Django 5.2 on 2025-05-02 12:36

import data.validate
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_alter_baseinfo_base_address_alter_baseinfo_base_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baseinfo',
            options={'verbose_name': 'Подразделение', 'verbose_name_plural': 'Подразделения'},
        ),
        migrations.AddField(
            model_name='baseinfo',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='titles/', verbose_name='Логотип подразделения'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='description',
            field=models.TextField(default='Здесь должно быть описание объекта, позволяющее легко его идентифицировать.\n                Здесь могут быть его характеристики, цвет, объем, системные данные и т.п.', validators=[data.validate.validate_description_length], verbose_name='Описание'),
        ),
    ]
