# Generated by Django 5.2 on 2025-04-20 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_alter_qrcode_objects_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='inventory_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='Инвентаризационный номер'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Инвентаризационный объект'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Балансовая стоимость'),
        ),
    ]
